### ISSUE TITLE
Error While Installing Csq in Ubuntu

### ISSUE THREAD

**Issue by WithSJ** [CsqLang/Csq3#5]
![Screenshot_20221217_172430](https://user-images.githubusercontent.com/44628192/208240656-742b96b6-d72c-42cd-a285-088138c0938c.png)

this error show to me... 
initializer_list' file not found

**Comment by AniketKumar2500** [comment]
Well let me examine

**Comment by AniketKumar2500** [comment]
could you please run a command :: ./csq for better understanding

**Comment by AniketKumar2500** [comment]
Ok thanks for pointing this out now the build.sh file is changed now it will work 👍🏻

**Comment by AniketKumar2500** [comment]
Now your issue is solved since build.sh is changes so now it will work.

**Comment by WithSJ** [comment]
Well csq executable now created but when i run build.sh these errors show 
and check this discussion plz. https://github.com/orgs/CsqLang/discussions/6#discussion-4673286s

![Screenshot_20221217_181702](https://user-images.githubusercontent.com/44628192/208242656-b6b4da23-c729-4bd4-a727-2778c4839bd2.png)

**Comment by AniketKumar2500** [comment]
these are errors which will cause no damage so just skip them

**Comment by WithSJ** [comment]
I create a "hello.csq" file and then run ./csq compiler but this error still occurs
![Screenshot_20221217_185448](https://user-images.githubusercontent.com/44628192/208244137-2b5c2d11-41f5-459b-8c3e-69129bf69368.png)

**Comment by AniketKumar2500** [comment]
These errors are just coming because g++ is compiling the comb.h and creating a library hence they will not cause any damage.

**Comment by AniketKumar2500** [comment]
type ./csq hello /home/jadam/Desktop/GITHUB/Csq3/
/home/jadam/Desktop/GITHUB/Csq3/ now run it.

**Comment by WithSJ** [comment]
No still got the same error

**Comment by AniketKumar2500** [comment]
Let me check once !

**Comment by AniketKumar2500** [comment]
go to Csq3/Modules/headers/ and delete file except comb.h

**Comment by WithSJ** [comment]
when I run this command it creates 2 files
hello.csqm and hello.cpp

**Comment by WithSJ** [comment]
> 

there is only one file comb.h

**Comment by WithSJ** [comment]
check this
![Screenshot_20221217_191032](https://user-images.githubusercontent.com/44628192/208244818-c8f8df4e-550c-4f0f-9c06-56fc72ba2299.png)

**Comment by AniketKumar2500** [comment]
thats fine

**Comment by WithSJ** [comment]
in comb.h error on 
#include <initializer_list>

and in csq.cpp  error on 
#include "Modules/typing.csqm"

**Comment by AniketKumar2500** [comment]
See it works on a new System also
![error](https://user-images.githubusercontent.com/90708238/208245116-3722f739-1bb5-43fb-85df-a9a58c5e3072.png)
Could you please describe how have you done the setup?

**Comment by AniketKumar2500** [comment]
I thinks you missed something.

**Comment by AniketKumar2500** [comment]
Steps:
1.clone the repo
2.cd Csq3
3.bash build.sh
4.try running ./csq && ./mcsq if runned you are good to go!

**Comment by WithSJ** [comment]
yes I did the same steps

**Comment by AniketKumar2500** [comment]
OK so will it be possible to send a short video of whole processes?

**Comment by AniketKumar2500** [comment]
https://user-images.githubusercontent.com/90708238/208246073-02a5122a-efc1-42ac-97b7-cd0530020a14.mp4
This is complete guide for setup.

**Comment by WithSJ** [comment]
I did the same steps but still, get that error 



hello.cpp
hello.csqm 

files created

when I compile it manually with g++ hello.cpp
it's working 

so. I think problem is here

![Screenshot_20221217_195543](https://user-images.githubusercontent.com/44628192/208246725-2af43dca-5071-4c3a-8ab3-e6192c323436.png)

**Comment by AniketKumar2500** [comment]
Yeah it looks like you don't have clang isn't it so yes change it to g++ and remove -O0

**Comment by AniketKumar2500** [comment]
change clang++ to g++ and run csq.cpp so now you are good to go!!
